Rebuild for Python 3.7, GCC 7, R 3.5.1, openBLAS 0.3.2 (#12)
* bump build number

* MNT: Re-rendered with conda-smithy 3.1.12 and pinning 2018.10.08

* Fix License name

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,37 +4,60 @@
 language: generic
 
 os: osx
-osx_image: beta-xcode6.1
+osx_image: xcode6.4
 
 env:
   matrix:
-    
-    - CONDA_PY=27
+    - CONFIG=osx_python2.7
+
   global:
     # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
     - secure: "kYCCKXuj3LcJpy/pLPf/Hp2MA0/HBTQ9B/BnQhD9Y0H4UXu8BUQty4btKIHA9QDvB/g/ErWpdq8WuE5DhQjocR2JZ66wt2Lt4s6m6Ox8wAK5plpQ3YGV9IplzVXyGp2GXlvCR/wuYFjerrQAOcO96MOrOH5CBmBQvZLsWVZGGpyb3NBrLbIhCY9Sb//p/0QYtnXefhli7oVmVZnX7b1ZqpUNBjmkE7yi9zH9IVFkhtSV5cJAFst4gjKPS0OdSYDnuyQEGxXVyxh/kbJ1nCz25rP5fUVvxWmTLbRxXJapx9e5yo+9xQLyuZxZPgprOqREZ8kYm800XfFMDPMY1R10hOaQSz1MyxrRYKQhQWP08u8GU3a6KdGI5+PExuH4SxMiUJrqO893U52K4R+JfPDCSeNMase8kW+Se5FIEX15CnG3ISTao/frjsGVVtDEi02ZdjnTd35ogyQbp3ITXU3TiBBRcQDe2pNwtwEoRQrY77d/h/g2deb4CwKGWWpodax91y5UiO/fHx21URKULU+zJPZcJDzbdPzHQx72jZASfH5USAWuc6QFUNqInTLwdWkid0a2QTt0VvcFLgrL6+QEtVdhIWxlwsigUhEtQn3PHT6EhAm4NbB1FfXCCPdTTde9JaIrr2wtCxbXlrTpzkMRI3UToY/BMnnoXXay+UZDszw="
 
 
 before_install:
+    # Fast finish the PR.
+    - |
+      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
+          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1
+
     # Remove homebrew.
-    - brew remove --force $(brew list)
-    - brew cleanup -s
-    - rm -rf $(brew --cache)
+    - |
+      echo ""
+      echo "Removing homebrew from Travis CI to avoid conflicts."
+      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
+      chmod +x ~/uninstall_homebrew
+      ~/uninstall_homebrew -fq
+      rm ~/uninstall_homebrew
+
 
 install:
+    # Install Miniconda.
     - |
-      MINICONDA_URL="http://repo.continuum.io/miniconda"
+      echo ""
+      echo "Installing a fresh version of Miniconda."
+      MINICONDA_URL="https://repo.continuum.io/miniconda"
       MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
-      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
+      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
       bash $MINICONDA_FILE -b
 
+    # Configure conda.
+    - |
+      echo ""
+      echo "Configuring conda."
       source /Users/travis/miniconda3/bin/activate root
-      conda config --add channels conda-forge
-      conda config --set show_channel_urls true
-      conda install --yes --quiet conda-forge-build-setup
+
+      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
+      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml
+
       source run_conda_forge_build_setup
 
-script:
-  - conda build ./recipe
+    # compiler cleanup
+    - |
+      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml
 
-  - upload_or_check_non_existence ./recipe conda-forge --channel=main
+script:
+  # generate the build number clobber
+  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
+  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
+  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
